udc_rec_sys/urls.py
from django.urls import path

from udc_rec_sys.views import index, article_upload

app_name = 'udc_rec_sys'

urlpatterns = [
    path('', index, name='index'),
    path('article_upload/', article_upload, name='article_upload'),
]

udcrec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('udc_rec_sys.urls', namespace='udc_rec_sys')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

udc_rec_sys/models.py
import os
import time

from django.db import models

from users.models import User


# Create your models here.


def save_article(instance, filename):
    ext = '.' + filename.split('.')[-1]
    name = filename.split(ext)[0]
    ext_time = '_' + str(time.strftime('%d.%m.%Y_%H.%M.%S', time.gmtime(time.time())))
    new_name = name + ext_time + ext
    return os.path.join(instance.dir_for_save, new_name)


class OntologyTable(models.Model):
    name = models.CharField(max_length=512, default='None')
    domain = models.CharField(max_length=512, blank=True, default='None')
    version = models.CharField(max_length=128, default='None')
    data = models.CharField(max_length=1048576, default='None')
    create_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Онтологии'

    def __str__(self):
        return str(self.name) + " | " + str(self.version)


class UdcTable(models.Model):
    udc_code = models.CharField(max_length=64, unique=True, default='None')
    name_ru = models.CharField(max_length=512, blank=True, default='None')
    name_en = models.CharField(max_length=512, blank=True, default='None')
    udc_map = models.CharField(max_length=1048576, default='None')
    exp_class_coefficient = models.CharField(max_length=4096, default='None')
    create_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Карты UDC'

    def __str__(self):
        return self.udc_code


class ResourceDownloadStatus(models.Model):
    name_ru = models.CharField(max_length=128, unique=True, default='None')
    name_en = models.CharField(max_length=128, unique=True, default='None')

    class Meta:
        verbose_name_plural = 'Статусы ресурсов'

    def __str__(self):
        return self.name_en


class ArticleStatus(models.Model):
    name_ru = models.CharField(max_length=128, unique=True, default='None')
    name_en = models.CharField(max_length=128, unique=True, default='None')

    class Meta:
        verbose_name_plural = 'Статусы статей'

    def __str__(self):
        return self.name_en


class ResourceDownload(models.Model):
    name = models.CharField(max_length=128, unique=True, default='None')
    link = models.CharField(max_length=512, unique=True, default='None')
    last_connection = models.DateTimeField(null=True)
    status = models.ForeignKey(ResourceDownloadStatus, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = 'Источники'

    def __str__(self):
        return self.name


class Article(models.Model):
    dir_for_save = 'articles_files'
    title = models.CharField(max_length=256, blank=True)
    file = models.FileField(upload_to=save_article)
    file_name = models.CharField(max_length=256, default='file')
    main_rec_udc = models.CharField(max_length=64, blank=True, default='None')
    other_rec_udc = models.CharField(max_length=256, blank=True, default='None')
    author_udc = models.CharField(max_length=256, blank=True, default='None')
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    resource = models.ForeignKey(ResourceDownload, on_delete=models.PROTECT)
    file_structure = models.CharField(max_length=1048576, default='None')
    onto_math_pro_version = models.CharField(max_length=128, blank=True)
    create_timestamp = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(ArticleStatus, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.file_name


class UserStash(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    article = models.ForeignKey(Article, on_delete=models.PROTECT)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Загрузки пользователей'

    def __str__(self):
        return f'{self.user.username} | Статья {self.article.file}'

udc_rec_sys/forms.py
from django import forms

from udc_rec_sys.models import Article


class ArticleUploadForm(forms.ModelForm):
    file = forms.FileField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input'
    }), required=True)

    class Meta:
        model = Article
        fields = ('file', )

udc_rec_sys/views.py
import os

from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import ugettext as _

from udc_rec_sys.forms import ArticleUploadForm
from udc_rec_sys.models import Article, UserStash, ResourceDownload, ArticleStatus

from udc_rec_sys.tasks import assign_udc_code


# Create your views here.


def index(request):
    context = {
        'title': _('ursv_index_title')
    }
    return render(request, 'udc_rec_sys/index.html', context)


@login_required
def article_upload(request):
    if request.method == 'POST':
        form = ArticleUploadForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            # check file format
            file_name, file_ext = os.path.splitext(request.FILES['file'].name)
            if file_ext != '.pdf':
                messages.info(request, 'Format Error: not a PDF or corrupted')
            else:
                resourse_id = ResourceDownload(id=1)  # User Download
                status = ArticleStatus(id=1)  # Uploaded
                article = Article(file=request.FILES['file'], file_name=request.FILES['file'].name,
                              owner=request.user, resource=resourse_id, status=status)
                article.save()
                UserStash.objects.create(user=request.user, article=article)

                # start task
                #assign_udc_code.delay(pdf_file=str(article.file))
                assign_udc_code.apply_async(args=[str(article.file)], queue='assign_code')
                return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = ArticleUploadForm()
    context = {
        'title': _('ursv_article_upload_title'),
        'form': form
    }
    return render(request, 'udc_rec_sys/article_upload.html', context)

udc_rec_sys/templates/udc_rec_sys/article_upload.html
{% extends 'udc_rec_sys/base.html'%}
{% load static %}
{% load i18n %}

{% block css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <div class="container">
        {% if messages or form.errors %}
        <div class="alert
                {% if messages %} {% if message.tags == info %}
                alert-warning {% else %} alert-success {% endif %}
                {% else %} alert-warning {% endif %}
                alert-dismissible fade show" role="alert" style="margin-top: 50px;">
            {% if messages %}
                {% for message in messages%}
                    {{ message }}
                {% endfor %}
            {% else %}
                {{ form.non_field_errors }}
            {% endif %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-lg-7">
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 50px;">
                    <h4 class="mt-3 mb-3">{% trans 'article_uploadHTML_title' %}</h4>
                    <form action="{% url 'udc_rec_sys:article_upload' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.file }}
                                    <label class="custom-file-label" for="{{ form.file.id_for_label }}">{% trans 'article_uploadHTML_select_article_label' %}</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 20px;">
                                <input class="btn btn-info btn-block" type="submit" value="{% trans 'article_uploadHTML_upload_button' %}">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
        {% include 'udc_rec_sys/article_upload_instruction.html' %}
    </div>
</div>
{% endblock %}

udc_rec_sys/templates/udc_rec_sys/article_upload_instruction.html
{% load i18n %}

<div class="col-lg-5" >
    <h1 class="mt-5">{% trans 'article_upload_instructionHTML_title' %}</h1>
    <p>
        {% trans 'article_upload_instructionHTML_msg1' %}
    </p>
    <p>
        {% trans 'article_upload_instructionHTML_msg2' %}
    </p>
</div>

udc_rec_sys/templates/udc_rec_sys/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'udc_rec_sys:index' %}"> {% trans 'baseHTML_navbar_header' %} </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'udc_rec_sys:article_upload' %}"> {% trans 'baseHTML_navbar_upload_article' %} <i class="fa-solid fa-cloud-arrow-down"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}"> {{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}"> {% trans 'baseHTML_navbar_logout' %} <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}"> {% trans 'baseHTML_navbar_login' %} <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="https://kit.fontawesome.com/821a23fdd5.js" crossorigin="anonymous"></script>
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

udc_rec_sys/templates/udc_rec_sys/index.html
{% extends 'udc_rec_sys/base.html'%}
{% load static %}
{% load i18n %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6" style="margin-top: 365px; margin-left: 25px">
                    <h1 class="mt-5">{% trans 'indexHTML_description_title' %}</h1>
                    <p>
                        {% trans 'indexHTML_description' %}
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'udc_rec_sys:article_upload' %}">
                            {% trans 'indexHTML_article_upload_button' %}
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

udc_rec_sys/templates/udc_rec_sys/userstash.html
{% if userstashes %}
{% load i18n %}

<div class="col-lg-5">
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        {% trans 'userstashHTML_title' %} <span class="badge badge-secondary badge-pill">{{ count_user_articles }}</span>
    </h4>
    {% for userstash in userstashes %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ userstash.article.file_name }}</h5>
            <p class="card-text">{% trans 'userstashHTML_recommended_udc' %}: {{ userstash.article.main_rec_udc}} </p>
            <p class="card-text">{% trans 'userstashHTML_potential_udc' %}: {{ userstash.article.other_rec_udc}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                <span class="text-muted">{{ userstash.article.status}}</span>
                <span class="text-muted">{{ userstash.article.create_timestamp}}</span>
            </li>
        </ul>
    </div>
    {% endfor %}
</div>
{% else %}
<h4 class="mt-3 mb-3 text-center">
    {% trans 'userstashHTML_if_empty_message' %}
</h4>
{% endif %}