udcrec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('udc_rec_sys.urls', namespace='udc_rec_sys')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    company = models.CharField(max_length=64, blank=True)
    position = models.CharField(max_length=64, blank=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from django.utils.translation import ugettext as _

from users.models import User

default_widget_class = 'form-control py-4'


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': _('uf_login_form_placeholder_username')
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': _('uf_login_form_placeholder_password')
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = default_widget_class


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': _('uf_registration_form_placeholder_first_name')
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': _('uf_registration_form_placeholder_last_name')
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': _('uf_registration_form_placeholder_username')
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': _('uf_registration_form_placeholder_email')
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': _('uf_registration_form_placeholder_password1')
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': _('uf_registration_form_placeholder_password2')
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = default_widget_class


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'readonly': True
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'readonly': True
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'company', 'position')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = default_widget_class

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from udc_rec_sys.models import UserStash, Article

# Create your views here.


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserLoginForm()
    context = {
        'title': _('uv_login_title'),
        'form': form
    }
    return render(request, 'users/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _('uv_register_success_msg'))
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': _('uv_register_title'),
        'form': form
    }
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=user)
    context = {
        'title': _('uv_profile_title'),
        'form': form,
        'userstashes': UserStash.objects.filter(user=user).order_by('-created_timestamp'),
        'count_user_articles': Article.objects.filter(owner=user).count()
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('udc_rec_sys:index'))

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="{% static 'vendor/jquery/jquery.slim.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html'%}
{% load static %}
{% load i18n %}

{% block content %}
<div class="col-lg-5">
    {% if messages or form.errors %}
    <div class="alert
            {% if messages %} alert-success {% else %} alert-warning {% endif %}
            alert-dismissible fade show" role="alert"
         style="margin-top: 50px;">
        {% if messages %}
        {% for message in messages%}
        {{ message }}
        {% endfor %}
        {% else %}
        {{ form.non_field_errors }}
        {% endif %}

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">{% trans 'loginHTML_header' %}</h3>
        </div>
        <div class="card-body">
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">{% trans 'loginHTML_username' %}</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password.id_for_label }}">{% trans 'loginHTML_password' %}</label>
                    {{ form.password }}
                </div>
                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                    <a class="small" href="#">{% trans 'loginHTML_forgot_password' %}</a>
                    <input class="btn btn-primary" type="submit" value="{% trans 'loginHTML_login_button' %}">
                </div>
            </form>
        </div>
        <div class="card-footer text-center">
            <div class="small"><a href="{% url 'users:register' %}">{% trans 'loginHTML_create_account_message' %}</a></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'udc_rec_sys/base.html'%}
{% load static %}
{% load i18n %}

{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">{% trans 'profileHTML_title' %}</h4>
            <form action="{% url 'users:profile' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label}}">
                                {% trans 'profileHTML_profile_first_name' %}</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label}}">
                                {% trans 'profileHTML_profile_last_name' %}</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.username.id_for_label}}">
                                {% trans 'profileHTML_profile_username' %}</label>
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.email.id_for_label}}">
                                {% trans 'profileHTML_profile_email' %}</label>
                            {{ form.email }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.company.id_for_label}}">
                                {% trans 'profileHTML_profile_company' %}</label>
                            {{ form.company }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.position.id_for_label}}">
                                {% trans 'profileHTML_profile_position' %}</label>
                            {{ form.position }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit"
                               value="{% trans 'profileHTML_profile_save_button' %}">
                    </div>
                </div>
            </form>

        </div>
        {% include 'udc_rec_sys/userstash.html' %}
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html'%}
{% load static %}
{% load i18n %}

{% block content %}
<div class="col-lg-7">
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert"
         style="margin-top: 50px;">
        {{ form.errors }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">{% trans 'registerHTML_header' %}</h3>
        </div>
        <div class="card-body">
            <form action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">{% trans 'registerHTML_first_name' %}</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">{% trans 'registerHTML_last_name' %}</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">{% trans 'registerHTML_username' %}</label>
                        {{ form.username }}
                    </div>
                    <div class="col-md-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">{% trans 'registerHTML_email' %}</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">{% trans 'registerHTML_password' %}</label>
                            {{ form.password1 }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">{% trans 'registerHTML_password2' %}</label>
                            {{ form.password2 }}
                        </div>
                    </div>
                </div>
                <div class="form-group mt-4 mb-0">
                    <input class="btn btn-primary btn-block" type="submit" value="{% trans 'registerHTML_create_button' %}">
                </div>
            </form>
        </div>
        <div class="card-footer text-center">
            <div class="small"><a href="{% url 'users:login' %}">{% trans 'registerHTML_already_have_account' %}</a></div>
        </div>
    </div>
</div>
{% endblock %}